jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cypress dependencies
        uses: cypress-io/github-action@v2
        with:
          cache: 'true'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --config-file=cypress.config.js
